#!env/bin/python3
import click
import os
import sys

from util.storage import load
from util.local_search_results import Results, generate_results_file_name
import util.file_util as file_util
import util.plot.heatmap as heatmap_plot
import util.plot.csv as csv_plot
from util.misc import round_all_values


def __generate_file_name(base_name: str, n: int) -> str:
    return f"n={n}: {base_name}"


def __generate_intersection_heatmap(results: Results, directory: str, n: int, include_annotation: bool = True):
    file_name: str = __generate_file_name("intersection-heatmap", n)
    directory = file_util.create_dir(directory, agressive=True)

    l_values, k_values, z = results.get_intersection_sizes(n)
    z = round_all_values(M=z, num_points=1)

    heatmap_plot.graph_heatmap(
        x=l_values,
        y=k_values,
        z=z,
        directory=directory,
        file_name=file_name,
        min=0,
        max=results.planted_sizes[n],
        title=f"Size of Intersection with Planted Independent Set  \n (n={n}, size={results.planted_sizes[n]}) \n after Local Optimization on Headstart Set",
        x_axis_title="Size of Headstart Set (l)",
        y_axis_title="Size of Intersection in Headstart Set (k)",
        color=heatmap_plot.HeatMapColor.YELLOW_GREEN,
        include_annotation=include_annotation,
        plot_size = 10
    )
    

def __generate_density_heatmap(results: Results, directory: str, n: int, include_annotation: bool = True):
    file_name: str = __generate_file_name("density-heatmap", n)
    directory = file_util.create_dir(directory, agressive=True)

    l_values, k_values, z = results.get_densities(n)
    z = round_all_values(M=z, num_points=2)     # Round to two decimal points to make it readable

    heatmap_plot.graph_heatmap(
        x=l_values,
        y=k_values,
        z=z,
        directory=directory,
        file_name=file_name,
        min=0,
        max=1,
        title=f"Density of set after local optimization (n={n}, size={results.planted_sizes[n]})",
        x_axis_title="Size of Headstart Set (l)",
        y_axis_title="Size of Intersection in Headstart Set (k)",
        color=heatmap_plot.HeatMapColor.REDS,
        include_annotation=include_annotation,
        plot_size = 10
    )

def __generate_subset_size_heatmap(results: Results, directory: str, n: int, include_annotation: bool = True):
    file_name: str = __generate_file_name("subset-size-heatmap", n)
    directory = file_util.create_dir(directory, agressive=True)

    l_values, k_values, z = results.get_subset_sizes(n)
    z = round_all_values(M=z, num_points=2)     # Round to two decimal points to make it readable

    heatmap_plot.graph_heatmap(
        x=l_values,
        y=k_values,
        z=z,
        directory=directory,
        file_name=file_name,
        min=0,
        max=n,
        title=f"Sol. size after loc. opt. (n={n}, size={results.planted_sizes[n]})",
        x_axis_title="Headstart Set (l)",
        y_axis_title="Initial Intersection (k)",
        color=heatmap_plot.HeatMapColor.REDS,
        include_annotation=include_annotation,
        plot_size = 10
    )


@click.group()
def run():
    pass


@run.command()
@click.option("--include-annotation", required=False, is_flag=True, default=False, help="Flag with whether or not to include annotations on the graph.")
@click.option("--intersection-heatmap", required=False, is_flag=True, default=False, help="2d heatmap of the final intersection size with planted ind set.")
@click.option("--density-heatmap", required=False, is_flag=True, default=False, help="2d heatmap of resulting density of set after local optimization.")
@click.option("--subset-size-heatmap", required=False, is_flag=True, default=False, help="2d heatmap of the size of the resulting subset.")
@click.option("--all", required=False, is_flag=True, default=False, help="Flag to graph all possible graphs.")
@click.option("--today", required=False, is_flag=True, default=False, help="Flag to set results name to results generated today.")
def graph_results(include_annotation, intersection_heatmap: bool, density_heatmap: bool, subset_size_heatmap: bool, all: bool, today: bool):
    # TODO: Fix graphing large values by showing a subset of the sizes rather than all of them
    # TODO: Fix the title, etc. to be a bit quicker.
    #? Verify the user has selected at least one graph
    if not any([intersection_heatmap, density_heatmap, all]):
        click.secho("There are no graphs selected. Please provide one as an argument.")
        sys.exit(0)

    #? Check whether they said all
    if all:
        intersection_heatmap = True
        density_heatmap = True
        subset_size_heatmap = True


    #? Collect file name from user
    if not today: 
        pickle_name = click.prompt('Please enter the file for the results', type=str)
    else:
        pickle_name = f"results/{generate_results_file_name()}"

    if not pickle_name:
        click.secho("A file name must be provided", err=True)
        sys.exit(0)

    if not os.path.isfile(f"{pickle_name}.pkl"):
        click.secho(f"The file at {pickle_name}.pkl could not be found.", err=True)
        sys.exit(0)
    
    #? Load results information, error if we got weird loading
    results: Results = load(pickle_name)
    if not results:
        click.secho("Could not load results.", err=True)
        sys.exit(0)

    #? Prompt the user for the directory to store the graphs in
    # TODO: Move all these stupid prompts into arguments for testing / repeated usage
    results_directory = click.prompt("Please enter a directory to store the graphs in", type=str)


    #? Go through and graph the results
    for n in results.n_values:
        if intersection_heatmap:
            __generate_intersection_heatmap(results, results_directory,  n, include_annotation)
        if density_heatmap:
            __generate_density_heatmap(results, results_directory,  n, include_annotation)
        if subset_size_heatmap:
            __generate_subset_size_heatmap(results, results_directory, n, include_annotation)

@run.command()
@click.option("--results-name", required=False, help="The file to pull results from")
@click.option("--csv-dir", required=False, help="The name of the file to save to ")
@click.option("--today", required=False, is_flag=True, default=False, help="Flag to set results name to results generated today.")
def generate_csv(results_name: str, csv_dir: str, today: bool):
    if not results_name:
        if not today:
            results_name = click.prompt("Results Name")
        else:
            results_name = f"results/{generate_results_file_name()}"
    if not csv_dir:
        csv_dir = click.prompt("CSV Directory")

    if not os.path.isfile(f"{results_name}.pkl"):
        click.secho(f"The file at {results_name}.pkl could not be found.", err=True)
        sys.exit(0)
    
    results: Results = load(results_name)
    if not results:
        click.secho("Could not load results.", err=True)
        sys.exit(0)

    # Put the relevant data into csv format
    directory = file_util.create_dir(csv_dir, agressive=True)
    for n in results.n_values:
        l_values, k_values, densities = results.get_densities(n)
        l_values, k_values, intersection = results.get_intersection_sizes(n)
        l_values, k_values, subset_size = results.get_subset_sizes(n)

        csv_plot.write_2d_to_csv(k_values, l_values, densities, f"{directory}/densities(n={n})")
        csv_plot.write_2d_to_csv(k_values, l_values, intersection, f"{directory}/intersection(n={n})")
        csv_plot.write_2d_to_csv(k_values, l_values, subset_size, f"{directory}/subset_sizes(n={n})")

        
    


if __name__ == "__main__":
    run()