#!env/bin/python3
import click
import os
import sys

from util.storage import load
from util.local_search_results import Results
import util.plot as plot
from util.misc import round_all_values


def __generate_file_name(base_name: str, n: int) -> str:
    return f"n={n}: {base_name}"


def __generate_intersection_heatmap(results: Results, directory: str, n: int):
    file_name: str = __generate_file_name("intersection-heatmap", n)
    directory = plot.create_dir(directory, agressive=True)

    l_values, k_values, z = results.get_intersection_sizes(n)
    plot.graph_heatmap(
        x=l_values,
        y=k_values,
        z=z,
        directory=directory,
        file_name=file_name,
        min="0",
        max=str(results.planted_sizes[n]),
        title=f"Size of Intersection with Planted Independent Set (n={n}, size={results.planted_sizes[n]}) \n after Local Optimization on Headstart Set",
        x_axis_title="Size of Headstart Set (l)",
        y_axis_title="Size of Intersection in Headstart Set (k)"
    )
    

def __generate_density_heatmap(results: Results, directory: str, n: int):
    file_name: str = __generate_file_name("density-heatmap", n)
    directory = plot.create_dir(directory, agressive=True)

    l_values, k_values, z = results.get_densities(n)
    z = round_all_values(M=z, num_points=2)     # Round to two decimal points to make it readable

    plot.graph_heatmap(
        x=l_values,
        y=k_values,
        z=z,
        directory=directory,
        file_name=file_name,
        min="0",
        max=str(results.planted_sizes[n]),
        title=f"Density of set after local optimization (n={n}, size={results.planted_sizes[n]})",
        x_axis_title="Size of Headstart Set (l)",
        y_axis_title="Size of Intersection in Headstart Set (k)"
    )


@click.group()
def run():
    pass


@run.command()
@click.option("--intersection-heatmap", required=False, is_flag=True, default=False)
@click.option("--density-heatmap", required=False, is_flag=True, default=False)
def graph_results(intersection_heatmap: bool, density_heatmap: bool):
    #? Verify the user has selected at least one graph
    if not any([intersection_heatmap, density_heatmap]):
        click.secho("There are no graphs selected. Please provide one as an argument.")
        sys.exit(0)

    #? Collect file name from user
    pickle_name = click.prompt('Please enter the file for the results. The results must be in the results directory', type=str)
    if not pickle_name:
        click.secho("A file name must be provided", err=True)
        sys.exit(0)

    if not os.path.isfile(f"{pickle_name}.pkl"):
        click.secho(f"The file at {pickle_name}.pkl could not be found.", err=True)
        sys.exit(0)
    
    #? Load results information, error if we got weird loading
    results: Results = load(pickle_name)
    if not results:
        click.secho("Could not load results.", err=True)
        sys.exit(0)

    #? Prompt the user for the directory to store the graphs in
    # TODO: Move all these stupid prompts into arguments for testing / repeated usage
    results_directory = click.prompt("Please enter a directory to store the graphs in", type=str)


    #? Go through and graph the results
    for n in results.n_values:
        if intersection_heatmap:
            __generate_intersection_heatmap(results, results_directory,  n)
        if density_heatmap:
            __generate_density_heatmap(results, results_directory,  n)


   


if __name__ == "__main__":
    run()